language: r
r:
  - 3.3.2

sudo: false
cache: packages

addon:
  apt:
    packages:
      - libudunits2-dev

addons:
  postgresql: "9.3"

before_script:
  - psql -U postgres -c "create extension postgis;"

before_install:
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

r_github_packages:
  - jimhester/covr

after_success:
  - R -e 'covr::codecov()'
